export const TextJSON = {
  ROOT: {
    type: { resolvedName: 'Container' },
    isCanvas: true,
    props: {
      flexDirection: 'column',
      alignItems: 'flex-start',
      justifyContent: 'flex-start',
      fillSpace: 'no',
      padding: ['40', '40', '40', '40'],
      margin: ['0', '0', '0', '0'],
      background: { r: 255, g: 255, b: 255, a: 1 },
      color: { r: 0, g: 0, b: 0, a: 1 },
      shadow: 0,
      radius: 0,
      width: '800px',
      height: 'auto',
    },
    displayName: 'Container',
    custom: { displayName: 'App' },
    hidden: false,
    nodes: ['8Zeqy2Ols2', '_mVaLVVTEu', 'VbDr_19zn9'],
    linkedNodes: {},
  },
  '8Zeqy2Ols2': {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      fontSize: '12',
      textAlign: 'left',
      fontWeight: '500',
      color: { r: 196, g: 38, b: 38, a: 1 },
      margin: [0, 0, 0, 0],
      shadow: 0,
      text: '11111',
    },
    displayName: 'Text',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  _mVaLVVTEu: {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      fontSize: '12',
      textAlign: 'left',
      fontWeight: '500',
      color: { r: 92, g: 90, b: 90, a: 1 },
      margin: [0, 0, 0, 0],
      shadow: 0,
      text: 'Hi 22222',
    },
    displayName: 'Text',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  VbDr_19zn9: {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      fontSize: '12',
      textAlign: 'left',
      fontWeight: '500',
      color: { r: 92, g: 90, b: 90, a: 1 },
      margin: [0, 0, 0, 0],
      shadow: 0,
      text: 'Hi 33333',
    },
    displayName: 'Text',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
};

export const TextJSON2 = {
  ROOT: {
    type: { resolvedName: 'Container' },
    isCanvas: true,
    props: {
      flexDirection: 'column',
      alignItems: 'flex-start',
      justifyContent: 'flex-start',
      fillSpace: 'no',
      padding: ['40', '40', '40', '40'],
      margin: ['0', '0', '0', '0'],
      background: { r: 255, g: 255, b: 255, a: 1 },
      color: { r: 0, g: 0, b: 0, a: 1 },
      shadow: 0,
      radius: 0,
      width: '800px',
      height: 'auto',
    },
    displayName: 'Container',
    custom: { displayName: 'App' },
    hidden: false,
    nodes: [
      '_mVaLVVTEu',
      'VbDr_19zn9',
      'Ys7vBLrd2N',
      '8Zeqy2Ols2',
      'LWKmzBQITg',
    ],
    linkedNodes: {},
  },
  '8Zeqy2Ols2': {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      fontSize: '12',
      textAlign: 'left',
      fontWeight: '500',
      color: { r: 196, g: 38, b: 38, a: 1 },
      margin: [0, 0, 0, 0],
      shadow: 0,
      text: '11111',
    },
    displayName: 'Text',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  _mVaLVVTEu: {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      fontSize: '12',
      textAlign: 'left',
      fontWeight: '500',
      color: { r: 92, g: 90, b: 90, a: 1 },
      margin: [0, 0, 0, 0],
      shadow: 0,
      text: 'Hi 22222',
    },
    displayName: 'Text',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  VbDr_19zn9: {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      fontSize: '12',
      textAlign: 'left',
      fontWeight: '500',
      color: { r: 92, g: 90, b: 90, a: 1 },
      margin: [0, 0, 0, 0],
      shadow: 0,
      text: 'Hi 33333',
    },
    displayName: 'Text',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  Ys7vBLrd2N: {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      fontSize: '12',
      textAlign: 'left',
      fontWeight: '500',
      color: { r: 92, g: 90, b: 90, a: 1 },
      margin: [0, 0, 0, 0],
      shadow: 0,
      text: 'Hi there',
    },
    displayName: 'Text',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
  LWKmzBQITg: {
    type: { resolvedName: 'Container' },
    isCanvas: true,
    props: {
      flexDirection: 'column',
      alignItems: 'flex-start',
      justifyContent: 'flex-start',
      fillSpace: 'no',
      padding: ['0', '0', '0', '0'],
      margin: ['0', '0', '0', '0'],
      background: { r: 235, g: 224, b: 224, a: 1 },
      color: { r: 0, g: 0, b: 0, a: 1 },
      shadow: 0,
      radius: 0,
      width: '300px',
      height: '300px',
    },
    displayName: 'Container',
    custom: {},
    parent: 'ROOT',
    hidden: false,
    nodes: ['RTKGtwrM0J'],
    linkedNodes: {},
  },
  RTKGtwrM0J: {
    type: { resolvedName: 'Text' },
    isCanvas: false,
    props: {
      fontSize: '12',
      textAlign: 'left',
      fontWeight: '500',
      color: { r: 92, g: 90, b: 90, a: 1 },
      margin: [0, 0, 0, 0],
      shadow: 0,
      text: 'Hi there',
    },
    displayName: 'Text',
    custom: {},
    parent: 'LWKmzBQITg',
    hidden: false,
    nodes: [],
    linkedNodes: {},
  },
};
